language: php

os: linux

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 7.0
 - 7.1
 - 7.2
 - 7.3

services:
  - mysql
  - postgresql

env:
 global:
# - IGNORE_PATHS=jquery/jeditable,lib/sortable
  - IGNORE_NAMES=jquery.jeditable.js,sorttable.js

 jobs:
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
jobs:
 exclude:
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
 fast_finish: true

before_install:
# This disables XDebug which should speed up the build.
  - phpenv config-rm xdebug.ini
# This installs NodeJS which is used by Grunt, etc.
  - nvm install 8.9
  - nvm use 8.9
# Currently we are inside of the clone of your repository.  We move up two
# directories to build the project.
  - cd ../..
  - composer selfupdate
# Install this project into a directory called "ci".
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
# Update the $PATH so scripts from this project can be called easily.
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
#  - moodle-plugin-ci grunt
  - moodle-plugin-ci mustache
#  - moodle-plugin-ci shifter
#  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
